controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    riptide_controller:
      type: riptide_controllers/RiptideController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: riptide_1_imu_sensor
    frame_id: riptide_1_imu

riptide_controller:
  ros__parameters:
    imu_name: imu
    thruster_joint: thruster
    d_joint: d_fin
    p_joint: p_fin
    s_joint: s_fin