controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    pressure_broadcaster:
      type: riptide_broadcasters/PressureBroadcaster

    tail_broadcaster:
      type: riptide_broadcasters/TailBroadcaster

    immersion_controller:
      type: riptide_controllers/ImmersionController

    riptide_controller:
      type: riptide_controllers/RiptideController

    log_controller:
      type: riptide_controllers/LogController
    
    depth_controller:
      type: riptide_controllers/DepthController

pressure_broadcaster:
  ros__parameters:
    prefix: riptide_1
    sensor_name: pressure

tail_broadcaster:
  ros__parameters:
    prefix: riptide_1
    thruster_joint: thruster_joint
    d_joint: d_joint
    p_joint: p_joint
    s_joint: s_joint
    rc_name: rc

imu_sensor_broadcaster:
  ros__parameters:
    frame_id: riptide_1
    sensor_name: riptide_1_imu

riptide_controller:
  ros__parameters:
    imu_name: imu_sensor
    prefix: riptide_1
    thruster_joint: thruster_joint
    d_joint: d_joint
    p_joint: p_joint
    s_joint: s_joint
    K_fin: .2
    r_fin: .025

log_controller:
  ros__parameters:
    prefix: riptide_1
    linear_velocity_x_joint: riptide_controller/linear_velocity.x
    angular_velocity_x_joint: riptide_controller/angular_velocity.x
    angular_velocity_y_joint: riptide_controller/angular_velocity.y
    angular_velocity_z_joint: riptide_controller/angular_velocity.z
    imu_name: imu_sensor

immersion_controller:
  ros__parameters:
    prefix: riptide_1
    thruster_joint: thruster_joint
    d_joint: d_joint
    p_joint: p_joint
    s_joint: s_joint
    thruster_velocity: 350.
    fin_angle: 0.4
    phase_1_duration: 1.5
    phase_2_duration: 6.

depth_controller:
  ros__parameters:
    pressure_name: riptide_1_pressure_sensor
    imu_name: riptide_1_imu_sensor
    orientation_reference_joint: log_controller
    K: 0.4
    r: 1.
    yaw: -1.4
    roll: 0.
    thruster_velocity: 200.